import { create } from 'zustand';
import { persist } from 'zustand/middleware';

// Type for the keyring structure based on what's generated by createEdDsaJwk()
export interface ImportKeyring {
    publicJwk: any; // The public JWK key
    privateJwk?: any; // The private JWK key (optional for security)
    [key: string]: any; // Allow for additional properties
}

interface ImportIdentityState {
    exportKeyring: ImportKeyring | null;
    identityHostUrl: string;
    setExportKeyring: (exportKeyring: ImportKeyring | null) => void;
    setIdentityHostUrl: (url: string) => void;
    clearExportKeyring: () => void;
}

export const useImportIdentityStore = create<ImportIdentityState>()(
    persist(
        (set) => ({
            exportKeyring: null,
            identityHostUrl: 'https://matchwise.ai/import',
            setExportKeyring: (exportKeyring) => set({ exportKeyring }),
            setIdentityHostUrl: (url) => set({ identityHostUrl: url }),
            clearExportKeyring: () => set({ exportKeyring: null }),
        }),
        {
            name: 'import-identity-storage',
        }
    )
);
