AWSTemplateFormatVersion: '2010-09-09'
Description: 'Agentic Profile Example Webapp CDN'

Parameters:
  StackName:
    Type: String
    Description: Lowercase project identifier used in resource names and tags
    AllowedPattern: '^[a-z0-9-]+$'
    ConstraintDescription: StackName must be lowercase letters, numbers, and dashes only

  Stage:
    Type: String
    Description: Deployment stage
    AllowedValues: [staging, prod]

  ProdDomainName:
    Type: String
    Default: ''
    Description: Custom domain name for the website (prod)

  NakedDomainName:
    Type: String
    Default: ''
    Description: Optional naked domain name for the production website

  StagingDomainName:
    Type: String
    Default: ''
    Description: Custom domain name for the website (staging)

  Route53HostedZoneId:
    Type: String
    Default: ''
    Description: Route53 Hosted Zone ID for custom domain

  CertificateArn:
    Type: String
    Default: ''
    Description: ACM certificate ARN for custom domain


Resources:
  # S3 Bucket for Website Content
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 
        - '${StackName}-${Stage}-${StackIdSuffix}'
        - StackIdSuffix: !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3000
      Tags:
        - Key: StackName  
          Value: !Ref StackName
        - Key: Stage
          Value: !Ref Stage

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases: !If 
          - HasCustomDomain
          - !If 
            - UseProdAndNakedDomain
            - [!Ref ProdDomainName, !Ref NakedDomainName]
            - !If 
              - UseProdDomain
              - [!Ref ProdDomainName]
              - !If
                - UseNakedDomain
                - [!Ref NakedDomainName]
                - [!Ref StagingDomainName]
          - !Ref 'AWS::NoValue'
        ViewerCertificate: !If
          - HasCustomDomain
          - AcmCertificateArn: !Ref CertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        Origins:
          - Id: S3Origin
            DomainName: !Sub '${WebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com'
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
              OriginReadTimeout: 30
              OriginKeepaliveTimeout: 5
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # Managed-CachingOptimized
        CacheBehaviors:
          - PathPattern: "index.html"
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # Managed-CachingDisabled
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 400
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100
        HttpVersion: http2
        IPV6Enabled: true
      Tags:
        - Key: StackName
          Value: !Ref StackName
        - Key: Stage
          Value: !Ref Stage

  # S3 Bucket Policy for Static Website Hosting
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: WebsiteBucket
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowPublicReadAccess
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${WebsiteBucket.Arn}/*'

  # CloudWatch Log Group for CloudFront
  CloudFrontLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/cloudfront/${StackName}-${Stage}'
      RetentionInDays: 30
      Tags:
        - Key: StackName
          Value: !Ref StackName
        - Key: Stage
          Value: !Ref Stage

  # Route 53 DNS Record
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasPrimaryDomain
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      Name: !If [UseProdDomain, !Ref ProdDomainName, !Ref StagingDomainName]
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront always uses this HostedZoneId
        EvaluateTargetHealth: false

  NakedDnsRecord:
    Type: AWS::Route53::RecordSet
    Condition: UseNakedDomain
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      Name: !Ref NakedDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

Conditions:
  IsProd: !Equals [!Ref Stage, 'prod']
  HasProdDomain: !Not [ !Equals [ !Ref ProdDomainName, '' ] ]
  HasStagingDomain: !Not [ !Equals [ !Ref StagingDomainName, '' ] ]
  HasNakedDomain: !Not [ !Equals [ !Ref NakedDomainName, '' ] ]
  UseProdDomain: !And [ !Condition IsProd, !Condition HasProdDomain ]
  UseStagingDomain: !And [ !Not [!Condition IsProd], !Condition HasStagingDomain ]
  UseNakedDomain: !And [ !Condition IsProd, !Condition HasNakedDomain ]
  HasPrimaryDomain: !Or [ !Condition UseProdDomain, !Condition UseStagingDomain ]
  UseProdAndNakedDomain: !And [ !Condition UseProdDomain, !Condition UseNakedDomain ]
  HasCustomDomain: !Or [ !Condition HasPrimaryDomain, !Condition UseNakedDomain ]

Outputs:
  WebsiteBucketName:
    Description: 'S3 Bucket Name for Website Content'
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteBucketName'

  WebsiteBucketArn:
    Description: 'S3 Bucket ARN for Website Content'
    Value: !GetAtt WebsiteBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteBucketArn'

  WebsiteBucketUrl:
    Description: 'S3 Static Website URL'
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteBucketUrl'

  CloudFrontDistributionId:
    Description: 'CloudFront Distribution ID'
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDistributionId'

  CloudFrontDomainName:
    Description: 'CloudFront Distribution Domain Name'
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDomainName'

  WebsiteUrl:
    Description: 'Website URL'
    Value: !If
      - UseProdDomain
      - !Sub 'https://${ProdDomainName}'
      - !If
        - UseStagingDomain
        - !Sub 'https://${StagingDomainName}'
        - !If
          - UseNakedDomain
          - !Sub 'https://${NakedDomainName}'
          - !Sub 'https://${CloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteUrl'